apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  name: trigger-mg-rs-backup
  namespace: demo
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: mg-rs-backup
