apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: mops-replicaset-upgrade
  namespace: demo
spec:
  type: UpdateVersion
  databaseRef:
    name: mg-rs
  upgrade:
    targetVersion: 5.0.3
