apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-sh
  namespace: demo
spec:
  version: "4.4.6"
  shardTopology:
    configServer:
      replicas: 3
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              memory: "1Gi"
    mongos:
      replicas: 1
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              memory: "1Gi"
    shard:
      replicas: 3
      shards: 1
      storage:
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
      configSecret:
        name: shard-config
      podTemplate:
        spec:
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              memory: "1Gi"
  storageType: Durable
  terminationPolicy: WipeOut
