apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rs
  namespace: demo
spec:
  version: "4.4.6"
  sslMode: requireSSL
  tls:
    issuerRef:
      name: mongo-ca-issuer
      kind: Issuer
      apiGroup: "cert-manager.io"
    certificates:
      - alias: client
        emailAddresses:
          - kcdblrorg@googlegroups.com
  clusterAuthMode: x509
  replicaSet: 
    name: "replicaset"
  replicas: 3
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
  init:
   script:
     configMap:
       name: init-script
  configSecret:
    name: custom-config
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        interval: 30s
        labels:
          release: prometheus
  terminationPolicy: DoNotTerminate
